### ISSUE TITLE
ErrorException `503 Service Unavailable`  : Server error: `POST https://translate.google.com/translate_a/s

### ISSUE THREAD

**Issue by price2b** [ben182/laravel-auto-translate#8]
First, thanks in advance for sharing this very useful package!.

I tried the package and receive:

```
| => php artisan autotrans:missing

   ErrorException  : Server error: `POST https://translate.google.com/translate_a/single?client=t&hl=en&dt=t&dt=bd&dt=at&dt=ex&dt=ld&dt=md&dt=qca&dt=rw&dt=rm&dt=ss&sl=en&tl=de&ie=UTF-8&oe=UTF-8&multires=1&otf=0&pc=1&trs=1&ssel=0&tsel=0&kc=1&tk=319219.191885` resulted in a `503 Service Unavailable` response:
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
<head><meta http-equiv="content-type" content="te (truncated...)


  at /Applications/MAMP/htdocs/domain/vendor/stichoza/google-translate-php/src/GoogleTranslate.php:312
    308|                     'query' => $queryUrl,
    309|                     'body'  => $queryBodyEncoded,
    310|                 ] + $this->options);
    311|         } catch (RequestException $e) {
  > 312|             throw new ErrorException($e->getMessage());
    313|         }
    314| 
    315|         $body = $response->getBody(); // Get response body
    316| 

  Exception trace:

  1   Stichoza\GoogleTranslate\GoogleTranslate::getResponse("Activate")
      /Applications/MAMP/htdocs/domain/vendor/stichoza/google-translate-php/src/GoogleTranslate.php:223

  2   Stichoza\GoogleTranslate\GoogleTranslate::translate("Activate")
      /Applications/MAMP/htdocs/domain/vendor/ben182/laravel-auto-translate/src/Translators/SimpleGoogleTranslator.php:32

```
I dont know if Im missing any setup, like API personal key or similar. any help appreciated.

**Comment by ben182** [comment]
Hi,
thanks for pointing this out. It is an issue that I forgot to mention in the readme. Currently I use [this](https://github.com/Stichoza/google-translate-php) package for the translator. Google Translate does offer an API but its not free. There is a free contingent but for simplicity I choosed the package since it does not require any API configuration. It creates HTTP calls to the Google Translate web app so there is a rate limitation if you have a lot of translations. When I tested this local I never got this exception but it is mentioned [here](https://github.com/Stichoza/google-translate-php#known-limitations) in the package readme. So a wordaround for now would be to only translate 1 file at a time. You can simply put all the files in a temp folder and then translate them step by step. But for now you are pretty much banned from using Google Translate for a couple of hours I guess. I will work on a proper solution now. Helpful would be letting the translator sleep for 1-2 seconds after each translation but that could take a lot of time. A better solution would be to implement another google translate translator that uses the official API. The free contingent is very large.

**Comment by price2b** [comment]
Thank you so much for your response!. excellent package anyway, I believe its the first one addressing this kind of need. I will work with temp files. thank you!.

**Comment by HDVinnie** [comment]
@ben182 I also ran into this issue. Maybe it would be better to dispatch the translations to Jobs with a delay that meets Googles rate limits?

**Comment by ben182** [comment]
Yes that would be an option. The rate limit is pretty much unknown since it fakes human translations. So if we spoof to human timing for translations it may work. I will work on this tomorrow and figure a delay or something out.

**Comment by ben182** [comment]
@HDVinnie can I ask u how many translations you wanted to translate?

**Comment by HDVinnie** [comment]
@ben182 My application has the following languages. I do plan to add more but at the moment English has a lot more then the rest. So I need to get the other lang file up to date. This package would save a great amount of time keeping them up to date with main english language.

https://github.com/HDInnovations/UNIT3D/tree/master/resources/lang

1210 Keys in `en`
